name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@de22e16c4711fca50c816cc9081563429d1cf563
        with:
          diagnostic-endpoint:
      - name: Build
        run: |
          nix build --print-build-logs
          cd result && find * -type f
